# Generated by Django 4.1.3 on 2022-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='name',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='itemdepartment',
            new_name='itemstudname',
        ),
        migrations.RenameField(
            model_name='names',
            old_name='department',
            new_name='Student_name',
        ),
        migrations.AddField(
            model_name='details',
            name='Student_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
