# Generated by Django 4.1.3 on 2022-11-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_details_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='itemstudname',
            new_name='sports_item',
        ),
        migrations.RenameField(
            model_name='names',
            old_name='Student_name',
            new_name='sports',
        ),
    ]
